### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by wbinnssmith** [rmm5t/liquidmetal#9]
Would you mind publishing liquidmetal to npm? Looks like everything is ready (package.json with a proper main field, cjs export in the library itself). 

Thanks!

**Comment by rmm5t** [comment]
Done: https://www.npmjs.com/package/liquidmetal

I don't use npm very much, so please let me know if anything else could be improved with that.

**Comment by wbinnssmith** [comment]
Thanks!
